config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show, :new, :create, :edit, :update]

  resources :blogs do
    collection do
      get :published
      get :unpublished
    end
    member do
      patch :publish
    end
    resources :comments, only: [:create, :index, :destroy]
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    if user.admin?
      can :manage, :all
    else
      # Blogs
      can :read, Blog, published: true
      can :read, Blog, user_id: user.id
      can :create, Blog
      can :update, Blog, user_id: user.id
      can :destroy, Blog, user_id: user.id
      can :publish, Blog, user_id: user.id
      
      # Comments
      can :read, Comment
      can :create, Comment
      can :update, Comment, user_id: user.id
      can :destroy, Comment, user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  
  validates :user, presence: true

  scope :published, -> { where(published: true) }
  scope :unpublished, -> { where(published: false) }

  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
  belongs_to :user
  
  validates :user, presence: true

  validates :body, presence: true
  validate :blog_must_be_published

  private

  def blog_must_be_published
    if blog && !blog.published?
      errors.add(:blog, "must be published to allow comments")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :blogs, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.html { redirect_to root_path, alert: exception.message }
      format.json { render json: { error: exception.message }, status: :forbidden }
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :published, :unpublished]
  load_and_authorize_resource
  skip_authorize_resource only: [:index, :published, :unpublished] # We'll handle collection authorization manually if needed or rely on index logic
  before_action :set_blog, only: %i[ show edit update destroy publish ]

  # GET /blogs or /blogs.json
  def index
    benchmark_result = Benchmark.measure do
      # IMPROVEMENT: Use eager loading for user associations to prevent N+1 queries
      @blogs = Blog.includes(:user, comments: :user).all
    end
    
    Rails.logger.info "Blog Index - Query Time: #{benchmark_result.real.round(4)}s"
    
    respond_to do |format|
      format.html
      format.json do
        serialization_benchmark = Benchmark.measure do
          @json_response = BlogBlueprint.render(@blogs)
        end
        Rails.logger.info "Blog Index - Serialization Time: #{serialization_benchmark.real.round(4)}s"
        Rails.logger.info "Blog Index - Total Time: #{(benchmark_result.real + serialization_benchmark.real).round(4)}s"
        render json: @json_response
      end
    end
  end

  # GET /blogs/published
  def published
    @blogs = Blog.published
    render :index
  end

  # GET /blogs/unpublished
  def unpublished
    @blogs = Blog.unpublished
    render :index
  end

  # GET /blogs/1 or /blogs/1.json
  def show
    respond_to do |format|
      format.html
      format.json { render json: BlogBlueprint.render(@blog, view: :with_comments) }
    end
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)
    @blog.user = current_user

    respond_to do |format|
      if @blog.save
        # Schedule auto-publish job for unpublished blogs (1 hour delay)
        if !@blog.published?
          PublishBlogJob.set(wait: 1.hour).perform_later(@blog.id)
          Rails.logger.info "Scheduled auto-publish for blog ##{@blog.id} in 1 hour"
        end
        
        format.html { redirect_to @blog, notice: "Blog was successfully created." }
        format.json { render json: BlogBlueprint.render(@blog), status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: "Blog was successfully updated.", status: :see_other }
        format.json { render json: BlogBlueprint.render(@blog), status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH /blogs/1/publish
  def publish
    begin
      BlogPublishingService.toggle_publish(@blog)
      status_text = @blog.published? ? "published" : "unpublished"
      
      respond_to do |format|
        format.html { redirect_to @blog, notice: "Blog was successfully #{status_text}.", status: :see_other }
        format.json { render json: BlogBlueprint.render(@blog), status: :ok, location: @blog }
      end
    rescue BlogPublishingService::PublishError => e
      respond_to do |format|
        format.html { redirect_to @blog, alert: e.message, status: :see_other }
        format.json { render json: { error: e.message }, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy!

    respond_to do |format|
      format.html { redirect_to blogs_path, notice: "Blog was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_blog

  def index
    @comments = @blog.comments
    
    respond_to do |format|
      format.html
      format.json { render json: CommentBlueprint.render(@comments) }
    end
  end

  def create
    @comment = @blog.comments.build(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @blog, notice: "Comment added" }
        format.json { render json: CommentBlueprint.render(@comment), status: :created }
      else
        format.html { redirect_to @blog, alert: @comment.errors.full_messages.join(", ") }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = @blog.comments.find(params[:id])
    @comment.destroy
    redirect_to @blog, notice: "Comment deleted"
  end

  private

  def set_blog
    @blog = Blog.find(params[:blog_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, notice: "User was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to users_path, notice: "User was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blogs/_blog.html.erb
<div id="<%= dom_id blog %>">
  <p>
    <strong>Title:</strong>
    <%= blog.title %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= blog.user ? blog.user.email : 'Unknown' %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= blog.body %>
  </p>

</div>

app/views/blogs/_blog_card.html.erb
<div class="blog-card">
  <h2><%= link_to blog.title, blog %></h2>
  <p><%= truncate(blog.body, length: 200) %></p>
  
  <div class="blog-meta">
    <span class="author">By <%= blog.user.email %></span>
    <span class="status <%= blog.published? ? 'published' : 'unpublished' %>">
      <%= blog.published? ? '✓ Published' : '✗ Unpublished' %>
    </span>
    <span class="date">
      Created <%= time_ago_in_words(blog.created_at) %> ago
    </span>
  </div>
  
  <div class="blog-actions">
    <%= link_to "View", blog, class: "btn btn-sm" %>
    <%= link_to "Edit", edit_blog_path(blog), class: "btn btn-sm" %>
    <%= button_to blog.published? ? "Unpublish" : "Publish", 
                  publish_blog_path(blog), 
                  method: :patch, 
                  class: "btn btn-sm" %>
  </div>
</div>

app/views/blogs/_blog_card.html.haml
-# HAML version of blog card partial
-# Demonstrates partials with locals in HAML

.blog-card
  %h2
    = link_to blog.title, blog
  %p= truncate(blog.body, length: 200)
  
  .blog-meta
    %span.status{class: blog.published? ? 'published' : 'unpublished'}
      = blog.published? ? '✓ Published' : '✗ Unpublished'
    %span.date
      Created
      = time_ago_in_words(blog.created_at)
      ago
  
  .blog-actions
    = link_to "View", blog, class: "btn btn-sm"
    = link_to "Edit", edit_blog_path(blog), class: "btn btn-sm"
    = button_to blog.published? ? "Unpublish" : "Publish", publish_blog_path(blog), method: :patch, class: "btn btn-sm"

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Show this blog", @blog %> |
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Blogs</h1>

<!-- Navigation for filtering -->
<div class="blog-filters">
  <%= link_to "All Blogs", blogs_path, class: "filter-link" %>
  <%= link_to "Published", published_blogs_path, class: "filter-link" %>
  <%= link_to "Unpublished", unpublished_blogs_path, class: "filter-link" %>
</div>

<div id="blogs">
  <% if @blogs.any? %>
    <% @blogs.each do |blog| %>
      <%= render partial: "blogs/blog_card", locals: { blog: blog } %>
    <% end %>
  <% else %>
    <p class="no-blogs">No blogs found.</p>
  <% end %>
</div>

<%= link_to "New blog", new_blog_path, class: "btn btn-primary" %>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @blog %>

<div>
  <%= link_to "Edit this blog", edit_blog_path(@blog) %> |
  <%= link_to "Back to blogs", blogs_path %>

  <%= button_to "Destroy this blog", @blog, method: :delete %>
</div>

<hr>

<!-- Comments Section -->
<%= render partial: "comments/list", locals: { comments: @blog.comments } %>

<hr>

<!-- Comment Form (only show if blog is published) -->
<% if @blog.published? %>
  <h3>Leave a Comment</h3>
  <%= render partial: "comments/form", locals: { blog: @blog, comment: @blog.comments.build } %>
<% else %>
  <p><em>Comments are disabled for unpublished blogs.</em></p>
<% end %>

app/views/comments/_comment.html.erb
<div class="comment" id="comment_<%= comment.id %>">
  <div class="comment-body">
    <%= simple_format(comment.body) %>
  </div>
  <div class="comment-meta">
    <small>By <%= comment.user.email %> | Posted <%= time_ago_in_words(comment.created_at) %> ago</small>
    <%= link_to "Delete", blog_comment_path(comment.blog, comment), 
                method: :delete, 
                data: { confirm: "Are you sure?" },
                class: "delete-link" %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [@blog, @blog.comments.build], local: true, class: "comment-form") do |form| %>
  <% if comment.errors.any? %>
    <div class="error-messages">
      <h3><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h3>
      <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body, "Add a comment:" %>
    <%= form.text_area :body, rows: 4, placeholder: "Write your comment here...", required: true %>
  </div>

  <div class="actions">
    <%= form.submit "Post Comment", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/comments/_form.html.haml
-# HAML version of the comment form
-# This demonstrates HAML syntax as an alternative to ERB

= form_with(model: [blog, comment], local: true, class: "comment-form") do |form|
  - if comment.errors.any?
    .error-messages
      %h3
        = pluralize(comment.errors.count, "error")
        prohibited this comment from being saved:
      %ul
        - comment.errors.full_messages.each do |message|
          %li= message

  .field
    = form.label :body, "Add a comment:"
    = form.text_area :body, rows: 4, placeholder: "Write your comment here...", required: true

  .actions
    = form.submit "Post Comment", class: "btn btn-primary"

app/views/comments/_list.html.erb
<div class="comments-section">
  <h3>Comments (<%= comments.count %>)</h3>
  
  <% if comments.any? %>
    <div class="comments-list">
      <%= render partial: "comments/comment", collection: comments %>
    </div>
  <% else %>
    <p class="no-comments">No comments yet. Be the first to comment!</p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render "form", user: @user %>

<%= link_to "Show", @user, class: "btn" %> |
<%= link_to "Back to Users", users_path, class: "btn" %>

app/views/users/index.html.erb
<h1>Users</h1>

<%= link_to "New User", new_user_path, class: "btn" %>

<div class="users-list">
  <% @users.each do |user| %>
    <div class="user-card">
      <p><strong>Email:</strong> <%= user.email %></p>
      <div class="actions">
        <%= link_to "Show", user_path(user) %>
        <%= link_to "Edit", edit_user_path(user) %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render "form", user: @user %>

<%= link_to "Back to Users", users_path, class: "btn" %>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>

<%= link_to "Edit", edit_user_path(@user), class: "btn" %>
<%= link_to "Back to Users", users_path, class: "btn" %>

<h2>Recent Blogs</h2>
<% @user.blogs.published.limit(5).each do |blog| %>
  <div class="blog-preview">
    <h3><%= link_to blog.title, blog %></h3>
    <span class="date"><%= time_ago_in_words(blog.created_at) %> ago</span>
  </div>
<% end %>